services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 5 && ollama pull qwen3.6:35b && wait"]
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama: